package ir.digixo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-09T17:44:53.610+03:30
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://digixo.ir/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://digixo.ir/HelloWorld/getHumanRequest", output = "http://digixo.ir/HelloWorld/getHumanResponse")
    @WebResult(name = "getHumanResponse", targetNamespace = "http://digixo.ir/", partName = "result")
    public GetHumanResponse getHuman(

        @WebParam(partName = "parameters", name = "getHuman", targetNamespace = "http://digixo.ir/")
        GetHuman parameters,
        @WebParam(partName = "myPartName", name = "arg0", targetNamespace = "http://digixo.ir/", header = true)
        Human myPartName
    );
}
